// Code generated by "stringer -type=Level"; DO NOT EDIT.

package interview

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AssociateOrProgrammer-1]
	_ = x[ProgrammerAnalyst-2]
	_ = x[SrProgrammer-3]
	_ = x[All-4]
}

const _Level_name = "AssociateOrProgrammerProgrammerAnalystSrProgrammerAll"

var _Level_index = [...]uint8{0, 21, 38, 50, 53}

func (i Level) String() string {
	i -= 1
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
