// Code generated by "stringer -type=Answer"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-1]
	_ = x[Wrong-2]
	_ = x[Neutral-3]
}

const _Answer_name = "OKWrongNeutral"

var _Answer_index = [...]uint8{0, 2, 7, 14}

func (i Answer) String() string {
	i -= 1
	if i < 0 || i >= Answer(len(_Answer_index)-1) {
		return "Answer(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Answer_name[_Answer_index[i]:_Answer_index[i+1]]
}
