// Code generated by "stringer -type=Command"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[exitCmd-0]
	_ = x[topicsCmd-1]
	_ = x[helpCmd-2]
	_ = x[useCmd-3]
	_ = x[clearScreenCommand-4]
	_ = x[pwdCommand-5]
	_ = x[noCmd-6]
}

const _Command_name = "exitCmdtopicsCmdhelpCmduseCmdclearScreenCommandpwdCommandnoCmd"

var _Command_index = [...]uint8{0, 7, 16, 23, 29, 47, 57, 62}

func (i Command) String() string {
	if i < 0 || i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
