// Code generated by "stringer -type=Command"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[exitCmd-0]
	_ = x[topicsCmd-1]
	_ = x[helpCmd-2]
	_ = x[useCmd-3]
	_ = x[clearScreenCmd-4]
	_ = x[pwdCmd-5]
	_ = x[noCmd-6]
	_ = x[startCmd-7]
	_ = x[printCmd-8]
	_ = x[nextQuestionCmd-9]
	_ = x[previousQuestionCmd-10]
	_ = x[viewCmd-11]
	_ = x[rightAnswerCmd-12]
	_ = x[wrongAnswerCmd-13]
	_ = x[mehAnswerCmd-14]
	_ = x[finishCmd-15]
	_ = x[increaseLevelCmd-16]
	_ = x[decreaseLevelCmd-17]
	_ = x[ignoreLevelCmd-18]
	_ = x[showLevelCmd-19]
	_ = x[showStatsCmd-20]
	_ = x[setAssociateProgrammerLevelCmd-21]
	_ = x[setProgrammerAnalystLevelCmd-22]
	_ = x[setSRProgrammerLevelCmd-23]
	_ = x[validateQuestionsCmd-24]
	_ = x[countCmd-25]
	_ = x[createComment-26]
	_ = x[createQuestion-27]
}

const _Command_name = "exitCmdtopicsCmdhelpCmduseCmdclearScreenCmdpwdCmdnoCmdstartCmdprintCmdnextQuestionCmdpreviousQuestionCmdviewCmdrightAnswerCmdwrongAnswerCmdmehAnswerCmdfinishCmdincreaseLevelCmddecreaseLevelCmdignoreLevelCmdshowLevelCmdshowStatsCmdsetAssociateProgrammerLevelCmdsetProgrammerAnalystLevelCmdsetSRProgrammerLevelCmdvalidateQuestionsCmdcountCmdcreateCommentcreateQuestion"

var _Command_index = [...]uint16{0, 7, 16, 23, 29, 43, 49, 54, 62, 70, 85, 104, 111, 125, 139, 151, 160, 176, 192, 206, 218, 230, 260, 288, 311, 331, 339, 352, 366}

func (i Command) String() string {
	if i < 0 || i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
