// Code generated by "stringer -type=Command"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[exitCmd-0]
	_ = x[exitInterviewFileCmd-1]
	_ = x[topicsCmd-2]
	_ = x[helpCmd-3]
	_ = x[useCmd-4]
	_ = x[clearScreenCmd-5]
	_ = x[pwdCmd-6]
	_ = x[noCmd-7]
	_ = x[startCmd-8]
	_ = x[printCmd-9]
	_ = x[nextQuestionCmd-10]
	_ = x[previousQuestionCmd-11]
	_ = x[viewCmd-12]
	_ = x[rightAnswerCmd-13]
	_ = x[wrongAnswerCmd-14]
	_ = x[mehAnswerCmd-15]
	_ = x[finishCmd-16]
	_ = x[loadCmd-17]
	_ = x[increaseLevelCmd-18]
	_ = x[decreaseLevelCmd-19]
	_ = x[ignoreLevelCmd-20]
	_ = x[showLevelCmd-21]
	_ = x[showStatsCmd-22]
	_ = x[setAssociateProgrammerLevelCmd-23]
	_ = x[setProgrammerAnalystLevelCmd-24]
	_ = x[setSRProgrammerLevelCmd-25]
	_ = x[validateQuestionsCmd-26]
	_ = x[countCmd-27]
}

const _Command_name = "exitCmdexitInterviewFileCmdtopicsCmdhelpCmduseCmdclearScreenCmdpwdCmdnoCmdstartCmdprintCmdnextQuestionCmdpreviousQuestionCmdviewCmdrightAnswerCmdwrongAnswerCmdmehAnswerCmdfinishCmdloadCmdincreaseLevelCmddecreaseLevelCmdignoreLevelCmdshowLevelCmdshowStatsCmdsetAssociateProgrammerLevelCmdsetProgrammerAnalystLevelCmdsetSRProgrammerLevelCmdvalidateQuestionsCmdcountCmd"

var _Command_index = [...]uint16{0, 7, 27, 36, 43, 49, 63, 69, 74, 82, 90, 105, 124, 131, 145, 159, 171, 180, 187, 203, 219, 233, 245, 257, 287, 315, 338, 358, 366}

func (i Command) String() string {
	if i < 0 || i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
